bloodofspring:
  telegram_id: 1044385209
  # ID группы, из которой будут пересылаться сообщения
  source_group_id: -1003226485859
  # ID канала, куда будут пересылаться сообщения
  target_channel_id: -1002000006931